import { NUMBER_OF_QUESTIONS } from '../workers/src/koi-polloi'

export const QUESTIONS = [
  'Name a reptile.',
  'What is the best way to cook an egg?',
  'Name a famous John.',
  'What is the best type of pasta?',
  'What is the best day of the week?',
  'What is the best fast food restaurant?',
  'What is the best season?',
  'Name a planet.',
  'Name a cocktail.',
  'What is the worst coin?',
  'How many times should you shower in a week?',
  'Name something in the kitchen.',
  'What is the best song by The Beatles?',
  'What is the latest hour you can have coffee?',
  'What is the earliest hour you can have beer?',
  'Name an American city starting with S.',
  'Name one of the wonders of the world.',
  'What is the biggest animal you could beat up?',
  'What is the last thing you do before going to sleep?',
  'How many pairs of socks should one own?',
  'What is the worst month of the year?',
  'What is the best pizza topping?',
  'Name the best dessert.',
  'Name an animal starting with R.',
  'Who is the best superhero?',
  'Name a famous landmark.',
  'What is the best sport to watch?',
  'What is the easiest sport to learn?',
  'What is the most popular karaoke song?',
  'What is the worst household chore?',
  'What is the best flavor of ice cream?',
  'What is the best sleeping position?',
  'Name an occupation starting with J.',
  'Name something you do when you wake up in the morning.',
  'Name a famous video game character.',
  'Name something inside your wallet.',
  'Name something you would bring to the beach.',
  'Name a healthy food.',
  'Name something you would bring on a camping trip.',
  'Name a rivalry between two brands.',
  'Name an item you might buy in a souvenir store.',
  'Name a carnival food.',
  'Name a word that rhymes with horse.',
  'Name a water sport.',
  'Name a food you might find in a school cafeteria.',
  'Name a place that is filled with people who do not want to be there.',
  'Name something specific you make sure to clean before company comes over.',
  'Name an animal that is easy to imitate in charades.',
  'What is the phone app you use the most?',
  'Name something you fill with air.',
  'Name something you wish you learned in school.',
  'Name something a lot of people are afraid of.',
  'Name something that makes you itch.',
  'What is the best kids food?',
  'Name something you close your eyes to do.',
  'Name something you do multiple times a day.',
  'Name a vegetable you dislike eating.',
  'Name a reason for being late to work.',
  'Name something that would be bad to forget to pack on a trip.',
  'What is something you never leave home without?',
  'Name a kitchen appliance.',
  'Name something that comes in pairs.',
  'What is the worst school subject?',
  'Name a popular comedy TV series.',
  'Name a popular board game.',
  'What is the most dangerous job?',
  'Name something people leave on their nightstand.',
  'What is a popular housewarming gift?',
  'What is a good activity for a first date?',
  'What is the best thing to spread on toast?',
  'What is the best coffee drink?',
  'Name an animal starting with B.',
  'Name an animal starting with E.',
  'Name a country starting with M.',
  'Name something that makes you think of France.',
  'Name a type of flower.',
  'What was the best movie made in the last 10 years?',
  'Name a popular singer.',
  'Name a singer/band who would be great to see in concert.',
  'What superpower would you like to have?',
  'Name a country starting with C.',
  'Name a country starting with S.',
  'What language do you wish you knew?',
  'What is the best Thanksgiving dish?',
  'What is the best flavor of cake?',
  'If you were an Olympic athlete, what would be your sport?',
  'What is the latest hour you can take a nap?',
]

console.assert(NUMBER_OF_QUESTIONS === QUESTIONS.length)
