name = "worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-20"

[build]
command = "yarn && yarn test && yarn build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "KOI_POLLOI", class_name = "KoiPolloi"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["KoiPolloi"]
