name: frontend

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
        node_version:
          - 14

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn build
